### ISSUE TITLE
ValueError: Variable <tf.Variable 'psi/bias:0' shape=(1,) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

### ISSUE THREAD

**Issue by ankitlohiya212** [sciann/sciann#11]
Python = 3.7.9
sciann = 0.5.4.0

Code Snippet Run :
```
import sciann as sn
    
t = sn.Variable("t")
x = sn.Variable("x")
y = sn.Variable("y")

p , psi = sn.Functional (["p", "psi"] , [t, x, y] , 8*[20] , 'tanh', kernel_initializer='uniform').split()
lamb1 = sn.Parameter(0.0, inputs=[x,y], name='lamb1')
lamb2 = sn.Parameter(0.0, inputs=[x,y], name='lamb2')

u , v = sn.math.diff(psi, y), -sn.math.diff(psi, x)
u_t , v_t = sn.math.diff(u, t), sn.math.diff(v, t)
u_x , u_y = sn.math.diff(u, x), sn.math.diff(u, y)
v_x , v_y = sn.math.diff(v, x), sn.math.diff(v, y)
u_xx , u_yy = sn.math.diff(u, x, order=2) , sn.math.diff(u, y, order=2)
v_xx , v_yy = sn.math.diff(v, x ,order=2) , sn.math.diff (v, y, order=2)
p_x , p_y = sn.math.diff(p, x), sn.math.diff(p, y)

L1 = u_t + p_x + lamb1 *( u * u_x + v * u_y ) - lamb2 *( u_xx + u_yy )
L2 = v_t + p_y + lamb1 *( u * v_x + v * v_y ) - lamb2 *( v_xx + v_yy )
L3 = u
L4 = v

m = sn.SciModel([t, x, y], [L1, L2, L3, L4], "mse", "adam")

m.train([t_train, x_train, y_train],\
        ['zeros', 'zeros', u_train , v_train ], \
        batch_size=64 , epochs=10000)
```

Full Error Message
``` Traceback (most recent call last):
  File "NavierStokes_sciann.py", line 291, in <module>
    batch_size=64 , epochs=10000)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\sciann\models\model.py", line 452, in train
    **kwargs
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training.py", line 727, in fit
    use_multiprocessing=use_multiprocessing)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 675, in fit
    steps_name='steps_per_epoch')
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 189, in model_iteration
    f = _make_execution_function(model, mode)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training_arrays.py", line 566, in _make_execution_function
    return model._make_execution_function(mode)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training.py", line 2183, in _make_execution_function
    self._make_train_function()
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\engine\training.py", line 2115, in _make_train_function
    params=self._collected_trainable_weights, loss=self.total_loss)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 498, in get_updates
    grads = self.get_gradients(loss, params)
  File "C:\Users\ashut\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\keras\optimizer_v2\optimizer_v2.py", line 396, in get_gradients
    "K.argmax, K.round, K.eval.".format(param))
ValueError: Variable <tf.Variable 'psi/bias:0' shape=(1,) dtype=float32> has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.
```

**Comment by sciann** [comment]
This is a Keras issue - it requires a value for every output of the network but here you have none for Psi. 

Add a trivial target on Psi and it should work. E.g.:

`L5 = psi*0.0`
`L5_data = 'zero'`
